#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: docker.io/clusterzx/paperless-ai
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 2.7.6

paperlessai:
  openai:
    # -- Enable OpenAI API
    # @default -- false
    enable: true
    # -- OpenAI API key
    # @default -- ""
    apiKey: ""
    # -- The name of existing secret containing a `openaiApiKey` key to configure OpenAI API key
    # @default -- ""
    existingSecret: ""
    # -- OpenAI model
    # @default -- gpt-4o-mini
    model: "gpt-4o-mini"

  ollama:
    # -- Enable Ollama API
    # @default -- false
    enable: false
    # -- Ollama API URL
    # @default -- http://localhost:11434
    url: "http://localhost:11434"
    # -- Ollama model
    # @default -- llama3.2
    model: "llama3.2"

  azure:
    # -- Enable Azure API
    # @default -- false
    enable: false
    # -- Azure OpenAI endpoint
    # @default -- ""
    endpoint: ""
    # -- Azure API key
    # @default -- ""
    apiKey: ""
    # -- The name of existing secret containing a `azureApiKey` key to configure Azure API key
    # @default -- ""
    existingSecret: ""
    # -- Azure deployment name
    # @default -- ""
    deploymentName: ""
    # -- Azure API version
    # @default -- ""
    apiVersion: ""

  # -- Custom system prompt for document processing
  # @default -- ""
  systemPrompt: ""
  # -- Scan interval in cron format
  # @default -- "*/30 * * * *"
  scanInterval: "*/30 * * * *"
  # -- Enable processing of predefined documents
  # @default -- no
  processPredefinedDocuments: "no"
  # -- Tags for document processing
  # @default -- ""
  tags: ""
  # -- Add a tag to AI-processed documents
  # @default -- no
  addAiProcessedTag: "no"
  # -- Tag name to be used for AI-processed documents
  # @default -- ai-processed
  aiProcessedTagName: "ai-processed"
  # -- Enable prompt-based tags
  # @default -- no
  usePromptTags: "no"
  # -- Tags to trigger prompt selection
  # @default -- ""
  promptTags: ""
  # -- Paperless Authentication Settings
  paperless:
    # -- Paperless API URL
    # @default -- http://localhost:8000
    apiUrl: "http://localhost:8000"
    # -- Paperless API token
    # @default -- ""
    apiToken: ""
    # -- Paperless username
    # @default -- ""
    username: ""
    # -- An existing secret containing the paperless credentials
    existingSecret:
      # -- Define the name of an existing Secret
      # @default -- ""
      name: ""
      # -- Define the key within the Secret for the API Token for Paperless
      # @default -- ""
      apiTokenKey: ""
      # -- Define the key within the Secret for the username for Paperless
      # @default -- ""
      usernameKey: ""
  # -- Process only new documents
  # @default -- yes
  processOnlyNewDocuments: "yes"
  # -- Use existing data (skip fresh download)
  # @default -- no
  useExistingData: "no"
  # -- Disable automatic processing
  # @default -- no
  disableAutomaticProcessing: "no"

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 3000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    retain: true
    mountPath: /app/data
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi
