{{/* Append the hardcoded settings */}}
{{- define "radarr.hardcodedValues" -}}
{{- end }}

{{- $_ := merge .Values (include "radarr.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
