#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/home-operations/sabnzbd
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 4.5.1

# -- Security Context for the qBittorrent container
# @default -- See [values.yaml](./values.yaml)
securityContext:
  runAsUser: 1001
  runAsGroup: 1001

podSecurityContext:
  fsGroup: 1001
  fsGroupChangePolicy: "OnRootMismatch"

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: true
    retain: true
    mountPath: /config
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi
  # -- Configure downloads volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  downloads:
    enabled: false
    retain: true
    mountPath: /downloads
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi