apiVersion: v2
name: pterodactyl-panel
description: "Pterodactyl® is a free, open-source game server management panel built with PHP, React, and Go."
home: https://charts.hydaz.com/charts/pterodactly-panel/
icon: https://pterodactyl.io/logos/pterry.svg
type: application
version: 0.1.3
# renovate datasource=docker depName=ghcr.io/pterodactyl/panel
appVersion: v1.11.10
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 1.5.1
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.7.0
    condition: redis.enabled
sources:
  - https://github.com/pterodactyl/panel
annotations:
  artifacthub.io/alternativeName: pterodactyl
  artifacthub.io/changes: |-
    - kind: fixed
      description: fix wing annotations
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/pterodactyl/panel
    - name: Chart Source
      url: https://github.com/hydazz/charts/tree/main/charts/pterodactly-panel
