{{/* Append the hardcoded settings */}}
{{- define "qbittorrent.hardcodedValues" -}}
env:
  {{- if .Values.vuetorrent.enabled }}
  QBT_Preferences__WebUI__AlternativeUIEnabled: "true"
  QBT_Preferences__WebUI__RootFolder: /addons/VueTorrent
  {{- end }}

sidecars:
  {{- if .Values.vuetorrent.enabled }}
  vuetorrent:
    image: "{{ .Values.vuetorrent.image.repository }}:{{ .Values.vuetorrent.image.tag }}"
    args:
      - --repo={{ .Values.vuetorrent.repo }}
      - --ref={{ .Values.vuetorrent.ref }}
      - --period={{ .Values.vuetorrent.period }}
      - --root={{ .Values.vuetorrent.root }}
      - --link={{ .Values.vuetorrent.link }}
    securityContext:
      runAsUser: {{ .Values.securityContext.runAsUser }}
      runAsGroup: {{ .Values.securityContext.runAsGroup }}
    volumeMounts:
      - name: addons
        mountPath: /addons
  {{- end }}

  {{- if .Values.gluetun.enabled }}
  gluetun:
    image: "{{ .Values.gluetun.image.repository }}:{{ .Values.gluetun.image.tag }}"
    env:
    {{- range $key, $value := .Values.gluetun.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
    {{- if .Values.gluetun.secretRef }}
    envFrom:
      - secretRef:
          name: {{ .Values.gluetun.secretRef }}
    {{- end }}
    securityContext:
      privileged: true
  {{- end }}

  {{- if and .Values.gluetun.enabled .Values.portForward.enabled }}
  port-forward:
    image: "{{ .Values.portForward.image.repository }}:{{ .Values.portForward.image.tag }}"
    env:
    {{- range $key, $value := .Values.portForward.env }}
      - name: {{ $key }}
        value: {{ $value | quote }}
    {{- end }}
  {{- end }}
{{- end }}

{{- $_ := merge .Values (include "qbittorrent.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
