{{ if .Values.wings.enabled }}
{{- range .Values.wings.instances }}
---
apiVersion: v1
kind: Service
metadata:
  name: wing-{{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: wing-{{ .name }}
  namespace: {{ $.Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .ip }}
    ports:
      - port: {{ .port }}
{{- end }}

{{- if and .Values.wings.enabled .Values.wings.ingressClassName .Values.wings.tlsSecretName .Values.wings.corsAllowOrigin }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wing-ingress
  namespace: {{ $.Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.wings.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-methods: GET, POST, OPTIONS
    nginx.ingress.kubernetes.io/cors-allow-headers: DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  ingressClassName: {{ .Values.wings.ingressClassName }}
  tls:
    - hosts:
{{- range .Values.wings.instances }}
        - {{ .to }}
{{- end }}
      secretName: {{ .Values.wings.tlsSecretName }}
  rules:
{{- range .Values.wings.instances }}
    - host: {{ .to }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wing-{{ .name }}
                port:
                  number: {{ .port }}
{{- end }}
{{- end }}
{{- end }}