apiVersion: v2
name: paperless-ngx
description: "A community-supported supercharged version of paperless: scan, index and archive all your physical documents"
home: https://charts.hydazz.com/charts/paperless-ngx/
icon: https://raw.githubusercontent.com/paperless-ngx/paperless-ngx/b948750/src-ui/src/assets/logo-notext.svg
type: application
version: 0.2.0
# renovate datasource=docker depName=ghcr.io/paperless-ngx/paperless-ngx
appVersion: 2.15.1
kubeVersion: ">=1.22.0-0"
keywords:
  - documents
  - ocr
  - paper
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.5.1
  - name: postgresql
    version: 16.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 20.7.0
    condition: redis.enabled
sources:
  - https://github.com/paperless-ngx/paperless-ngx
annotations:
  artifacthub.io/alternativeName: paperless
  artifacthub.io/changes: |-
    - kind: changed
      description: Update ghcr.io/paperless-ngx/paperless-ngx docker tag to v2.15.1
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/paperless-ngx/paperless-ngx
    - name: Chart Source
      url: https://github.com/hydazz/charts/tree/main/charts/paperless-ngx
