#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s-labs/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/home-operations/qbittorrent
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 5.1.0

# -- VueTorrent Git sync settings
vuetorrent:
  # -- Enable VueTorrent sidecar (install theme)
  # @default -- true
  enabled: true
  image:
    repository: registry.k8s.io/git-sync/git-sync
    tag: v4.4.0
  repo: https://github.com/VueTorrent/VueTorrent.git
  ref: latest-release
  period: 6h
  root: /add-ons
  link: vuetorrent

# -- Gluetun VPN container settings
gluetun:
  # -- Enable Gluetun sidecar
  # @default -- true
  enabled: false
  image:
    repository: ghcr.io/qdm12/gluetun
    tag: v3.40.0
  env:
    # -- Configure Gluetun settings under this key.
    #    [[ref]](https://github.com/qdm12/gluetun?tab=readme-ov-file#setup)
    # @default -- See [values.yaml](./values.yaml)
    # VPN_SERVICE_PROVIDER: custom
    # VPN_TYPE: wireguard
    # VPN_INTERFACE: wg0
    # WIREGUARD_ENDPOINT_PORT:
    # VPN_PORT_FORWARDING: on
    # VPN_PORT_FORWARDING_PROVIDER:
    # FIREWALL_INPUT_PORTS: 8080
    # FIREWALL_OUTBOUND_SUBNETS: 10.233.64.0/18,10.233.0.0/18 # Cluster and Node CIDR
  # -- Secret containing Wireguard or OpenVPN Environment Variables
  # @default -- qbittorrent-vpn-secret
  secretRef: qbittorrent-vpn-secret

# -- Port forwarding sync settings
portForward:
  # -- Enable port-forward sidecar
  # @default -- true
  enabled: false
  image:
    repository: ghcr.io/bjw-s-labs/gluetun-qb-port-sync
    tag: 0.0.4
  env:
    # -- Configure Port forwarding settings under this key.
    #    [ref]](https://github.com/bjw-s-labs/container-images/blob/main/apps/gluetun-qb-port-sync/script.sh)
    # @default -- See [values.yaml](./values.yaml)
    GLUETUN_CONTROL_SERVER_HOST: localhost
    GLUETUN_CONTROL_SERVER_PORT: 8000
    QBITTORRENT_HOST: localhost
    QBITTORRENT_WEBUI_PORT: 8080
    CRON_ENABLED: true
    CRON_SCHEDULE: "*/5 * * * *"
    LOG_TIMESTAMP: false

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 64m
    # hosts:
    #   - host: chart-example.local
    #     paths:
    #       - path: /
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: true
    retain: true
    mountPath: /config
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi
  # -- Configure downloads volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  downloads:
    enabled: false
    retain: true
    mountPath: /downloads
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi
