#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/blob/a081de5/charts/library/common/values.yaml
#

image:
  # -- Image repository
  repository: ghcr.io/ep1cman/unifi-protect-backup
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 0.13.0

upb:
  # -- UniFi Protect credentials and connection settings
  ufp:
    # -- UFP username (plain value, ignored if existingSecret is set)
    username: ""
    # -- UFP password (plain value, ignored if existingSecret is set)
    password: ""
    # -- Existing Secret settings
    existingSecret:
      # -- Define the name of an existing Secret containing the username and password
      # @default -- ""
      name: ""
      # -- Secret key to use for the UFP username
      # @default -- ""
      usernameKey: ""
      # -- Secret key to use for the UFP password
      # @default -- ""
      passwordKey: ""
    # -- UFP controller address
    # @default -- ""
    address: ""
    # -- UFP controller port
    # @default -- 443
    port: 443
    # -- Verify SSL certificate
    # @default -- true
    sslVerify: true

  # -- Rclone settings
  rclone:
    # -- Rclone retention policy
    # @default -- ""
    retention: "7d"
    # -- Destination path for Rclone
    # @default -- ""
    destination: ""
    # -- Extra Rclone arguments
    # @default -- ""
    args: ""
    # -- Extra Rclone purge arguments
    # @default -- ""
    purgeArgs: ""
    # -- Number of parallel uploads
    # @default -- ""
    parallelUploads: "1"
    # -- Rclone config file.
    #    This will create/overwrite the existing Rclone config.
    #    [[ref]](https://rclone.org/docs/)
    # @default -- See [values.yaml](./values.yaml)
    config: |
      [cloudflare]
      type = s3
      provider = Cloudflare
      access_key_id =
      secret_access_key =
      endpoint =
    # -- Existing Secret settings
    existingSecret:
      # -- Define the name of an existing Secret containing the rclone config
      # @default -- ""
      name: ""
      # -- Define the key within the existing Secret containing the rclone config
      # @default -- ""
      rcloneConfigKey: "rclone.conf"

  # -- Camera filtering settings
  camera:
    # -- Cameras to ignore
    # @default -- ""
    ignore: ""
    # -- Cameras to include
    # @default -- ""
    include: ""
    # -- Detection types to use
    # @default -- ""
  detectionTypes: ""

  # -- Event and download settings
  fileStructureFormat: "{camera_name}/{event.start:%Y-%m-%d}/{event.end:%Y-%m-%dT%H-%M-%S} {detection_type}.mp4"
  sqlitePath: "events.sqlite"
  downloadBufferSize: "512MiB"
  downloadRateLimit: ""
  maxEventLength: "7200"
  experimentalDownloader: false

  # -- Logging and purge settings
  colorLogging: false
  purgeInterval: "1d"
  skipMissing: false

  # -- Notification configuration
  appriseNotifiers: ""

env:
  # -- Set the container timezone
  TZ: UTC
  PUID: 1001
  PGID: 1001

service:
  main:
    enabled: false

persistence:
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: false
    retain: true
    mountPath: /config
    # storageClass: ""
    # accessMode: ReadWriteOnce
    # size: 1Gi
