{{/* Append the hardcoded settings */}}
{{- define "unpackerr.hardcodedValues" -}}
env:
{{- /* Global settings */ -}}
{{- range $key, $val := .Values.unpackerr.global }}
  UN_{{ $key | upper | replace "." "_" }}: "{{ $val }}"
{{- end }}

{{- /* Webserver settings */ -}}
{{- range $key, $val := .Values.unpackerr.webserver }}
  UN_WEBSERVER_{{ $key | upper | replace "." "_" }}: "{{ $val }}"
{{- end }}

{{- /* Services: sonarr, radarr, lidarr, readarr, whisparr */ -}}
{{- range $svc := list "sonarr" "radarr" "lidarr" "readarr" "whisparr" }}
  {{- $svcItems := index $.Values.unpackerr $svc }}
  {{- range $i, $item := $svcItems }}
  UN_{{ $svc | upper }}_{{ $i }}_URL: "{{ $item.url }}"
    {{- if $item.apiKey }}
  UN_{{ $svc | upper }}_{{ $i }}_API_KEY: "{{ $item.apiKey }}"
    {{- else if $item.apiKeySecret }}
  UN_{{ $svc | upper }}_{{ $i }}_API_KEY:
    valueFrom:
      secretKeyRef:
        name: "{{ $item.apiKeySecret.name }}"
        key: "{{ $item.apiKeySecret.key }}"
    {{- end }}
    {{- range $k, $v := $item }}
      {{- if and (ne $k "url") (ne $k "apiKey") (ne $k "apiKeySecret") }}
  UN_{{ $svc | upper }}_{{ $i }}_{{ $k | upper }}: "{{ $v }}"
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{- /* Folder watchers */ -}}
{{- range $i, $folder := .Values.unpackerr.folder }}
  {{- range $k, $v := $folder }}
  UN_FOLDER_{{ $i }}_{{ $k | upper }}: "{{ $v }}"
  {{- end }}
{{- end }}

{{- /* Webhook settings */ -}}
{{- range $i, $webhook := .Values.unpackerr.webhook }}
  {{- range $k, $v := $webhook }}
    {{- if eq $k "url" }}
      {{- if $v.secretRef }}
  UN_WEBHOOK_{{ $i }}_URL:
    valueFrom:
      secretKeyRef:
        name: "{{ $v.secretRef.name }}"
        key: "{{ $v.secretRef.key }}"
      {{- else }}
  UN_WEBHOOK_{{ $i }}_URL: "{{ $v }}"
      {{- end }}
    {{- else if eq $k "events" }}
      {{- range $j, $event := $v }}
  UN_WEBHOOK_{{ $i }}_EVENTS_{{ $j }}: "{{ $event }}"
      {{- end }}
    {{- else if eq $k "exclude" }}
      {{- range $j, $ex := $v }}
  UN_WEBHOOK_{{ $i }}_EXCLUDE_{{ $j }}: "{{ $ex }}"
      {{- end }}
    {{- else }}
  UN_WEBHOOK_{{ $i }}_{{ $k | upper | replace "." "_" }}: "{{ $v }}"
    {{- end }}
  {{- end }}
{{- end }}
{{- end -}}
{{- $_ := merge .Values (include "unpackerr.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.all" . }}
