site_name: gabe565 Helm Charts
site_url: https://charts.gabe565.com
site_author: Gabe Cook
site_description: >-
  A collection of Helm charts, based on the bjw-s common library chart.

repo_name: !ENV [REPO_NAME, "gabe565/charts"]
repo_url: !ENV [REPO_URL, "https://github.com/gabe565/charts"]

theme:
  name: material
  custom_dir: overrides
  logo: assets/icons/icon.webp
  favicon: assets/icons/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - content.code.copy
    - content.tooltips
  icon:
    repo: fontawesome/brands/github

extra:
  analytics:
    provider: google
    property: G-3R5THTGGHP

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - tags
  - privacy
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      exclude:
        - README.md
  - minify:
      minify_html: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
      css_files:
        - stylesheets/extra.css
  - mkdocs-simple-hooks:
      hooks:
        on_files: plugins.add_files:main
        on_page_markdown: plugins.filter_readmes:main
  - social:
      cards_layout_options:
        background_color: "#2a309a"

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - toc:
      permalink: true

watch:
  - overrides
